### PR TITLE
Feature/content type posts ids

### PR DESCRIPTION
**Pull request by XternalSoft**
This PR adds a new panel type: “Post IDs”.

image

With this new panel, the user can set a list of post IDs to be placed in the accordion.
I developed this feature for a user need to specifically want certain posts.
All the user has to do is enter the list of IDs separated by a comma.

image

I decided to make a new panel because the configuration is simpler than the Posts panel. And it was unnecessarily complex for the admin and the front end.

I hope you'll find it useful too.

### CODE REVIEW

**Comment by davidghi** [comment]
This could be useful, but another way to do it is to add a tag to all the posts that you want loaded and then use that tag in a Posts panel. Would this not work well enough for this scenario?

**Comment by XternalSoft** [comment]
It's an idea, but there are several concerns: 
- The user has to go and edit the posts to assign/remove the tag.
- With the use of a tag, it becomes impossible to precisely define the display order in the accordion. And this is a necessary condition.

**Comment by davidghi** [comment]
I understand. Having the ability to define a specific ordering of the posts can make this feature useful.

**Comment by XternalSoft** [comment]
Thanks !

**Pull request merged**
